<?php
namespace App\Common;

/**
* @author: Cecil Migayi
* @email: migayicecil@gmail.com
* @copyright: zapi, 2018
*
* Handle Username info
*/

class Username{
	protected $username;

	/**
	* Setter
	*
	* @param String (username)
	* @return void
	*/
	public function setUsername($username){
		$this->username = $username;
	}

	/**
	* Username validation
	*
	* @param void
	* @return String (username)
	*/
	public function validUsername(){
		if(empty($this->username)){
			//$this->log->error("Username cannot be empty!");
			throw new \Exception("Username cannot be empty!");
		}
		return $this->username;
	}

	/**
	* Username info is generated by the system
	*
	* @param void
	* @return String (username)
	*/
	public function generateUsername(){
		$alpha = "zap";
		$num = rand(1,10000);
		$this->username = $alpha."".$num;

		return $this->username;
	}	
}