<!doctype html>
<html lang="en">
	<head>
		<title></title>
		<meta charset="utf-8">
  		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

		<link rel="stylesheet" type="text/css" href="webui/css/style.css">

		<!-- jQuery library -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

		<!-- Popper JS -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

		<!-- Latest compiled JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script> 		
	</head>
	<body>
		<div class="container">

			<header>
				<nav class="navbar navbar-expand-sm bg-primary navbar-dark">
				  <a class="navbar-brand" href="#">Zapi</a>
				  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
				    <span class="navbar-toggler-icon"></span>
				  </button>
				  <div class="collapse navbar-collapse" id="collapsibleNavbar">
				    <ul class="navbar-nav">
				      <li class="nav-item">
				        <!-- Dropdown -->
					    <li class="nav-item dropdown">
					      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
					        Products
					      </a>
					      <div class="dropdown-menu">
					        <a class="dropdown-item" href="#">Stock</a>
					        <a class="dropdown-item" href="#">Sales</a>
					        <a class="dropdown-item" href="#">Suppliers</a>
					      </div>
					    </li>
				      </li>
				      <li class="nav-item">
				        <!-- Dropdown -->
					    <li class="nav-item dropdown">
					      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
					        Services
					      </a>
					      <div class="dropdown-menu">
					        <a class="dropdown-item" href="#">Sales</a>
					        <a class="dropdown-item" href="#">Suppliers</a>
					      </div>
					    </li>
				      </li>
				      <li class="nav-item">
				        <!-- Dropdown -->
					    <li class="nav-item dropdown">
					      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
					        Sales
					      </a>
					      <div class="dropdown-menu">
					        <a class="dropdown-item" href="#">Credit</a>
					        <a class="dropdown-item" href="#">Transactions</a>
					      </div>
					    </li>
				      </li>
				      <li class="nav-item">
				        <a class="nav-link" href="#">Suppliers</a>
				      </li> 
				      <li class="nav-item">
				        <a class="nav-link" href="#">Businesses</a>
				      </li> 
				      <li class="nav-item">
				        <a class="nav-link" href="#">Profile</a>
				      </li>
				    </ul>
				  </div>  
				</nav>
			</header>

			<div class="content">