<?php
require_once("vendor/autoload.php");

use App\Data\ServiceSale;
use App\Repositories\ServiceSaleRepository; 
use App\Middlewares\AddServiceSale;
use App\Common\ErrorLogger;

//initialize objects
$serviceSale= new ServiceSale();
$serviceSaleRepository = new ServiceSaleRepository();
$log = new ErrorLogger("add_service_sale");
$log = $log->initLog();

//Data validation
$businessId = 1;
$productId = 1;
$sellerId = 1;

/**
* Transaction number must be autogenerated
*/
$transactionNumber = "";

$fee = 500;
$payment = "Mpesa";
$receipt = "email";

//set data
$serviceSale->setBusinessId($businessId);
$serviceSale->setServiceId($productId);
$serviceSale->setSellerId($sellerId);
$serviceSale->setTransactionNumber($transactionNumber);
$serviceSale->setFee($fee);
$serviceSale->setPayment($payment);
$serviceSale->setReceipt($receipt);

//set repository
$addServiceSale = new AddServiceSale($serviceSaleRepository);

try{
	$serviceSale = $addServiceSale->createServiceSale($serviceSale);
	echo $serviceSale->getServiceSaleId()." ".$serviceSale->getServiceId();

}catch(\Exception $e){
	// logger
	$log->error("Error ".$e->getMessage());
}