<?php
require_once("vendor/autoload.php");

use App\Data\ProductSale;
use App\Repositories\ProductSaleRepository; 
use App\Middlewares\AddProductSale;
use App\Common\ErrorLogger;
use App\Common\TransactionNumber;

//initialize objects
$productSale = new ProductSale();
$productSaleRepository = new ProductSaleRepository();
$log = new ErrorLogger("add_product_sale");
$log = $log->initLog();
$transactionNumber = new TransactionNumber();

//Data validation
$businessId = 1;
$productId = 1;
$sellerId = 66;

/**
* Transaction number must be autogenerated
*/
$transactionNumber = $transactionNumber->getTransactionNumber();

$quantity = 5;
$cost = 500;
$payment = "Mpesa";
$receipt = "email";

//set data
$productSale->setBusinessId($businessId);
$productSale->setProductId($productId);
$productSale->setSellerId($sellerId);
$productSale->setTransactionNumber($transactionNumber);
$productSale->setQuantity($quantity);
$productSale->setCost($cost);
$productSale->setPayment($payment);
$productSale->setReceipt($receipt);

//set repository
$addProductSale = new AddProductSale($productSaleRepository);

try{
	$productSale = $addProductSale->createProductSale($productSale);
	echo $productSale->getProductSaleId()." ".$productSale->getProductId()." ".$transactionNumber;

}catch(\Exception $e){
	// logger
	$log->error("Error ".$e->getMessage());
}