<?php
require_once("vendor/autoload.php");

use App\Data\Owner;
use App\Repositories\OwnerRepository; 
use App\Middlewares\AddOwner;
use App\Common\Email;
use App\Common\Phone;
use App\Common\InputValidator;
use App\Common\Username;
use App\Common\Password;

//initialize objects
$owner = new Owner();
$ownerRepository = new OwnerRepository();
$email = new Email();
$phone = new Phone();
$username = new Username();
$password = new Password();
$inputValidator = new InputValidator();


// set repository
$addOwner = new AddOwner($ownerRepository);

// Data validation

// Firstname validation
//$fname = $_POST['fname'];
$fname = "Cilo";
$fname = $inputValidator->validateInput($fname);

// Lastname validation
//$lname = $_POST['lname'];
$lname = "Cilo";
$lname = $inputValidator->validateInput($lname);

// Email validation
//$ownerEmail = $_POST['email'];
$ownerEmail = "cilo@gmail.com";
$email->setEmail($ownerEmail); 
$ownerEmail = $email->validEmail();

// Phone validation
//$ownerPhone = $_POST['phone'];
$ownerPhone = "0718485173";
$phone->setPhoneNumber($ownerPhone);
$ownerPhone = $phone->validPhoneNumber();

// Username autogenerated
$ownerUsername = $username->generateUsername();
echo $ownerUsername."<br/>";

// Password autogenerated
$ownerPassword = $password->generatePassword();
echo $ownerPassword;
$password->setPassword($ownerPassword);
$ownerPassword = $password->encryptPassword();

// set data
$owner->setFname($fname);
$owner->setLname($lname);
$owner->setEmail($ownerEmail);
$owner->setPhone($ownerPhone);
$owner->setUsername($ownerUsername);
$owner->setPassword($ownerPassword);


if(empty($ownerEmail) || empty($ownerPhone)){
	//Validation failed 
	$info["status"] = false;
	$info["records"] = 0;
}else{
	$owner = $addOwner->createOwner($owner);	
	
	if($owner == null){
		//Validation failed 
		$info["status"] = false;
		$info["records"] = 0;
	}else{
		$info["status"] = true;
		$info["records"] = 1;	
		$data["owner_id"] = $owner->getOwnerId();
		$data["fname"] = $owner->getFname();
		$data["lname"] = $owner->getLname();
		$data["email"] = $owner->getEmail();
		$data["phone"] = $owner->getPhone();
		$data["password"] = $owner->getPassword();
		$data["date_time"] = $owner->getDateTime();
	}
}
$content["info"] = array();
$content["owner"] = array();
$main["content"] = array();

array_push($content["info"],$info);
array_push($content["owner"],$data);
array_push($main["content"],$content);

echo json_encode($main, true);